//
//  freedomTrailDescriptions.swift
//  FreedomTrailApp
//
//  Created by Sam Mailand on 4/3/16.
//  Copyright © 2016 Sam Mailand. All rights reserved.
//

import Foundation


let bostonCommonDescription = "The Common's purpose has changed over the years. It was once owned by William Blaxton (often given the modernized spelling \"Blackstone\"), the first European settler of Boston, until it was bought from him by the Puritan founders of the Massachusetts Bay Colony. During the 1630s, it was used by many families as a cow pasture. However, this only lasted for a few years, as affluent families bought additional cows, which led to overgrazing, a real-life example of the Tragedy of the commons. After grazing was limited in 1646 to 70 cows at a time, the Boston Common continued to host cows until they were formally banned from it in 1830 by Mayor Harrison Gray Otis."

let stateHouseDescription = "The original red-brick Bulfinch building contains the Governor's offices (on the west end) with the Massachusetts Senate occupying the former House of Representatives Chamber under the dome. The Massachusetts House of Representatives occupies a chamber on the west side of the Brigham addition. Hanging over this chamber is the \"Sacred Cod\", which was given to the House of Representatives in 1784 by a Boston merchant. The Sacred Cod symbolizes the importance of the fishing industry to the early Massachusetts economy. \n\nThe second floor under the dome is decorated by murals painted by artist Edward Brodney. Brodney won a competition to paint the first mural in a contest sponsored by the Works Progress Administration in 1936. It is entitled \"Columbia Knighting Her World War Disabled.\" Brodney could not afford to pay models, and friends and family posed. The model for Columbia was Brodney's sister Norma Brodney Cohen, and the model for the soldier on one knee in the foreground was his brother Fred Brodney. In 1938, he painted a second mural under the dome called \"World War Mothers.\" The models were again primarily friends and family members, with sister Norma sitting beside their mother Sarah Brodney. The New York Times notes that the murals are relatively rare examples of military art with women as their subjects."

let parkStreetChurchDescription = "The church is located adjacent to the historic Granary Burying Ground. It had its first worship service on January 10, 1810. The church became known as \"Brimstone Corner\", in part because of the fervent missionary character of its preaching, and in part because of the storage of gunpowder during the War of 1812. \n\nPark Street Church has a strong tradition of missions, evangelical doctrine, and application of Scripture to social issues as well as a notable list of Firsts. Edward Dorr Griffin (1770–1837) served as the first pastor of the Park Street Church and preached a famous series of Sunday evening sermons attacking the New Divinity. In 1816 Park Street Church joined with Old South Church to form the City Mission Society, a social service society to serve Boston's urban poor. \n\nIn 1826 Edward Beecher, the brother of Harriet Beecher Stowe and son of Lyman Beecher, a notable abolitionist, became pastor of the church. On July 4, 1829, William Lloyd Garrison delivered his Address to the Colonization Society at Park Street, making his first major public statement against slavery. From 1829–1831 Lowell Mason, a notable Christian composer, served as choirmaster and organist. The church hosted the debut of My Country, 'Tis of Thee, also known as America, by Samuel Francis Smith on July 4, 1831. Park Street also played a role in founding the First \"Homeland\" or American Mission to the then Sandwich Islands (now Hawaii), where that church still stands; the Handel and Haydn Society started there. Benjamin E. Bates, an industrialist who founded Bates College in Maine in 1855, was a Sunday school teacher and active attendant of Park Street in the mid-19th century. In 1857–58 evangelist, Charles Finney led a revival at Park Street which led the pastor, Andrew Leete Stone, to experience a spiritual awakening."

let granaryGroundDescription = "The Burying Ground was the third cemetery established in the city of Boston and dates to the year 1660. The need for the site arose because the land set aside for the city's first cemetery — King's Chapel Burying Ground, located a block east — was insufficient to meet the city's growing population. Early in its existence the area was known as the South Burying Ground until 1737 at which point it took on the name of the granary building which formerly stood on the site of what is now the Park Street Church. In May 1830 trees were planted in the area and an attempt was made to change the name to “Franklin Cemetery” to honor the family of Benjamin Franklin, but the effort failed."

let kingChapelDescription = "In 1749, construction began on the current stone structure, which was designed by Peter Harrison and completed in 1754. The stone church was built around the wooden church. When the stone church was complete, the wooden church was disassembled and removed through the windows of the new church. The wood was then shipped to Lunenburg, Nova Scotia where it was used to construct St. John's Anglican Church. That church was destroyed by fire on Halloween night, 2001. It has since been rebuilt. Originally, there were plans to add a steeple, although funding shortfalls prevented this from happening. \n\nDuring the American Revolution, the chapel sat vacant and was referred to as the \"Stone Chapel.\" The Loyalist families left for Nova Scotia and England, and those who remained reopened the church in 1782. It became Unitarian under the ministry of James Freeman, who revised the Book of Common Prayer along Unitarian lines in 1785. Although Freeman still considered King's Chapel to be Episcopalian, the Anglican Church refused to ordain him. The church still follows its own Anglican/Unitarian hybrid liturgy today. It is a member congregation of the Unitarian Universalist Association."

let chapelBuryingDescription = "King's Chapel Burying Ground was founded in 1630 as the first cemetery in the city of Boston. According to custom, the first interment was that of the land’s original owner, Isaac Johnson. It was Boston's only burial site for 30 years (1630-1660). After being unable to locate land elsewhere, in 1686 the local Anglican congregation was allotted land in the cemetery to build King's Chapel."

let benFranklinDescription = "Puritans placed a strong emphasis on education at every age level for their offspring, beginning at home, with a primary reason for this being in order to read the Bible, which was used for spiritual and moral instruction. Puritan leaders themselves were accustomed to the highest educational standards, with most of their minsters having graduated from Oxford or Cambridge University in England, and soon established Boston Latin School as the first secondary school in the United State, and was modeled after the European Latin School Model, which emphasized the learning of religion, Latin, and classical literature."

let oldBookStoreDescription = "From 1832 to 1865, it was home to Ticknor and Fields, a publishing company founded by William Ticknor, later renamed when he partnered with James Thomas Fields. For part of the 19th century, the firm was one of the most important publishing companies in the United States, and the Old Corner Bookstore became a meeting-place for such authors as Henry Wadsworth Longfellow, Ralph Waldo Emerson, Nathaniel Hawthorne, Charles Dickens, and Oliver Wendell Holmes, Sr. Ticknor and Fields rented out the whole building, using only the corner for a retail space. Other section of the building, particularly upstairs rooms and storefronts facing School Street, were in turn sublet to other businesses. After the death of Ticknor, Fields wanted to focus on publishing rather than the retail store. On November 12, 1864, he sold the Old Corner Bookstore to E. P. Dutton; Ticknor and Fields moved to Tremont Street. A succession of other publishing houses and booksellers followed Ticknor and Fields in the building."

let southMeetingHouseDescription = "After the Boston Massacre in 1770, yearly anniversary meetings were held at the church until 1775 featuring speakers such as John Hancock and Dr. Joseph Warren. In 1773 5,000 people met in the Meeting House to debate British taxation, and after the meeting a group raided three tea ships anchored nearby in what became known as the Boston Tea Party.\n\nIn 1775 the British occupied the Meeting House due to its association with the Revolutionary cause. The British gutted the building, filled it with dirt and then used the interior to practice horse riding. They destroyed much of the interior and stole various items including William Bradford's Of Plymouth Plantation (1620), a unique Pilgrim manuscript, hidden in Old South's tower.\n\nOld South Meeting House was almost destroyed in the Great Boston Fire of 1872, saved by the timely arrival of a fire engine from Portsmouth, New Hampshire, but the fire caused the city's residential districts to shift toward the Back Bay, away from the church. The congregation then built a new church building (the \"New\" Old South Church at Copley Square) which remains its home to this day. Once a year, on the Sunday before Thanksgiving, the Old South congregation returns to Old South Meeting House for services in its ancestral home."

let oldStateHouseDescription = "Today's brick Old State House was built in 1712–13, possibly designed by Robert Twelves; the previous building, the wooden Town House of 1657, had burned in the fire of 1711. A notable feature was the pair of seven-foot tall wooden figures depicting a lion and unicorn, symbols of the British monarchy.\n\nThe building housed a Merchant's Exchange on the first floor and warehouses in the basement. On the second floor, the east side contained the Council Chamber of the Royal Governor while the west end of the second floor contained chambers for the Courts of Suffolk County and the Massachusetts Supreme Judicial Court. The central portion contained the chambers for the elected Massachusetts Assembly. This chamber is notable for including public galleries, the first known example of such a feature being included in a chamber for elected officials in the English-speaking world."

let bostonMassacreDescription = "The Boston Massacre, known as the Incident on King Street by the British, was an incident on March 5, 1770, in which British Army soldiers killed five male civilians and injured six others. The incident was heavily propagandized by leading Patriots, such as Paul Revere and Samuel Adams, to fuel animosity toward the British authorities. British troops had been stationed in Boston, capital of the Province of Massachusetts Bay, since 1768 in order to protect and support crown-appointed colonial officials attempting to enforce unpopular Parliamentary legislation. Amid ongoing tense relations between the population and the soldiers, a mob formed around a British sentry, who was subjected to verbal abuse and harassment. He was eventually supported by eight additional soldiers, who were subjected to verbal threats and thrown objects. They fired into the crowd, without orders, instantly killing three people and wounding others. Two more people died later of wounds sustained in the incident. \n\nThe crowd eventually dispersed after Acting Governor Thomas Hutchinson promised an inquiry, but reformed the next day, prompting the withdrawal of the troops to Castle Island. Eight soldiers, one officer, and four civilians were arrested and charged with murder. Defended by the lawyer and future American president, John Adams, six of the soldiers were acquitted, while the other two were convicted of manslaughter and given reduced sentences. The men found guilty of manslaughter were sentenced to branding on their hand. Depictions, reports, and propaganda about the event, notably the colored engraving produced by Paul Revere (shown at right), further heightened tensions throughout the Thirteen Colonies."

let fanueuilHallDescription = "After the project of erecting a public market house in Boston had been discussed for some years, merchant Peter Faneuil offered, at a public meeting in 1740, to build a suitable edifice at his own cost as a gift to the town. There was a strong opposition to market houses, and although a vote of thanks was passed unanimously, his offer was accepted by a majority of only seven. Funded in part by profits from slave trading, the building was begun in Dock Square in September of the same year. It was built by artist John Smibert in 1740–1742 in the style of an English country market, with an open ground floor serving as the market house, and an assembly room above. According to Sean Hennessey, a National Park Service spokesman, some of Boston's early slave auctions were located near Faneuil Hall. The grasshopper weather vane on top of the hall is a well known symbol of Boston. In 1761 the hall was destroyed by fire, nothing but the brick walls remaining. It was rebuilt by the town in 1762. In 1775, during the British occupation of Boston, it was used for a theatre."

let paulRevereDescription = "The original three-story house was built about 1680, making it the oldest house in downtown Boston. It occupied the former site of the Second Church of Boston's parsonage, home to Increase Mather and Cotton Mather, which was destroyed in the Great Fire of 1676. Its first owner was Robert Howard, a wealthy merchant. His L-shaped townhouse contained spacious rooms and would have been enhanced by exterior features such as a second-floor overhang and casement windows. \n\nAs is typical of early Massachusetts Bay timber construction, the main block of the three-story dwelling consisted of four structural bays demarcated by heavy framing posts and overhead beams. The larger ground-floor room in this main block was dominated by its chimney bay and adjoining lobby entrance. Although some contemporary Boston houses had separate kitchen buildings, the two-story extension behind the Revere House was typical. As the Revere House was set quite close to neighbors, its double casement windows were installed in the rear elevation rather than the more common placement in a gable."

let northChurchDescription = "The Old North Church was built in December, 1723, and was inspired by the works of Christopher Wren, the British architect who was responsible for rebuilding London after the Great Fire. Timothy Cutler was the founding rector after serving as third rector of Yale College from 1719 to 1722. \n\nIn April 1775, Paul Revere told three Boston patriots to hang two lanterns in the steeple. These men were the church sexton Robert Newman and Captain John Pulling—the two of whom historian David Hackett Fischer suggests each carried one lantern up to the steeple—as well as Thomas Bernard, who stood watch for British troops outside the church. The lanterns were displayed to send a warning to Charlestown patriots across the Charles River about the movements of the British Army. Revere and William Dawes would later deliver the same message to Lexington themselves, but this lantern method was a fast way to inform the back-up riders in Charlestown about the movements of the British; these back-up riders planned to deliver the warning message to Lexington and Concord in case Revere and Dawes were arrested on the way."

let coppsHillDescription = "The cemetery was founded on February 20, 1659, when the town bought land on Copp's Hill from John Baker and Daniel Turell to start the \"North Burying Ground\". Now named \"Copp's Hill Burying Ground\" (although often referred to as \"Copp's Hill Burial Ground\"), it is the second oldest cemetery in Boston (second only to the King's Chapel Burying Ground founded in 1630). It contains more than 1200 marked graves, including the remains of various notable Bostonians from the colonial era into the 1850s. The first extension was made on January 7, 1708 when the town bought additional land from Judge Samuel Sewall and his wife Hannah. The land was part of a pasture which Mrs. Sewall had inherited from her father, John Hull, master of the mint."

let bunkerHillDescription = "The monument was one of the first in the United States. An earlier memorial at the site had been erected in memory of fallen Bunker Hill hero Dr. Joseph Warren, a Mason, in 1794 by King Solomon's Lodge of Masons, and was initially an 18 foot (5.5 m) wooden column topped with a gilt urn. In front of the obelisk is a statue of Col. William Prescott, a native of Groton, Massachusetts, another hero of Bunker Hill. According to popular stories, he coined the famous Revolutionary War phrase, \"Don't fire until you see the whites of their eyes\" during the battle. However, various writers attribute it to Putnam, Stark, Prescott or Gridley, while others question whether it was said at all.\n\nThe Monument is not on Bunker Hill, but instead on Breed's Hill, where most of the fighting in the misnamed Battle of Bunker Hill actually took place. The Monument Association, which had purchased the battlefield site, was forced to sell off all but the hill's summit in order to complete the monument."

let ussConstitutionDescription = "USS Constitution is a wooden-hulled, three-masted heavy frigate of the United States Navy, named by President George Washington after the Constitution of the United States of America. Launched in 1797, Constitution was one of six original frigates authorized for construction by the Naval Act of 1794 and the third constructed. Joshua Humphreys designed the frigates to be the young Navy's capital ships, and so Constitution and her sisters were larger and more heavily armed and built than standard frigates of the period. Constitution was built in the North End of Boston, Massachusetts, at Edmund Hartt's shipyard. Her first duties with the newly formed U.S. Navy were to provide protection for American merchant shipping during the Quasi-War with France and to defeat the Barbary pirates in the First Barbary War. \n\nConstitution is most famous for her actions during the War of 1812 against the United Kingdom, when she captured numerous merchant ships and defeated five British warships: HMS Guerriere, Java, Pictou, Cyane, and Levant. The battle with Guerriere earned her the nickname of \"Old Ironsides\" and public adoration that has repeatedly saved her from scrapping. She continued to serve as flagship in the Mediterranean and African squadrons, and circled the world in the 1840s. During the American Civil War, she served as a training ship for the United States Naval Academy. She carried US artwork and industrial displays to the Paris Exposition of 1878."



let bostonCommonSummary = "Established in 1634, Boston Common is America’s oldest public park."

let stateHouseSummary = "Designed by Charles Bulfinch, the Massachusetts State House was completed on January 11, 1798, and is widely acclaimed as one of the more magnificent public buildings in the country."

let parkStreetChurchSummary = "The church was founded in 1809, at the corner of Park and Tremont Streets, atop the site of Boston’s town grain storage building, or granary."

let granaryGroundSummary = "Established in 1660, some of America's most notable citizens rest here."

let kingChapelSummary = "In 1688, Royal Governor Andros directed that King’s Chapel be built on a town burying ground when no one in the city would sell the congregation desirable land on which to build a non-Puritan church."

let chapelBuryingSummary = "A fascinating historic cemetery, King's Chapel Burying Ground is located next to King’s Chapel on Tremont Street."

let benFranklinSummary = "Boston Latin School, founded on April 23, 1635, is the oldest public school in America."

let oldBookStoreSummary = "The oldest commercial building in Boston, the Old Corner Bookstore was built in 1718 as an apothecary shop and home on property that once belonged to Puritan dissident Anne Hutchinson."

let southMeetingHouseSummary = "Built in 1729, Old South Meeting House was not a church, but rather a meeting house for the Puritans to worship."

let oldStateHouseSummary = "The Old State House has stood as an emblem of liberty in Boston for over 300 years."

let bostonMassacreSummary = "The tensions that led to the Boston Massacre were the product of the occupation of Boston by Redcoats in 1768. "

let fanueuilHallSummary = "Often referred to as \"the home of free speech\" and the \"Cradle of Liberty,\" Faneuil Hall hosted America's first Town Meeting."

let paulRevereSummary = "Built around 1680, the Paul Revere House is the oldest remaining structure in downtown Boston and the only home on the Freedom Trail. "

let northChurchSummary = "Christ Church in the City of Boston, also known as Old North Church, is the oldest standing church building in Boston, having first opened its doors to worshippers on December 29, 1723."

let coppsHillSummary = "Named after shoemaker William Copp, Copp’s Hill Burying Ground is the final resting place and cemetery of merchants, artisans and craft people who lived in the North End. "

let bunkerHillSummary = "The Battle of Bunker Hill on June 17, 1775, was the first major battle of the Revolutionary War and predicted the character and outcome of the rest of the war."

let ussConstitutionSummary = "Launched in Boston in 1797, the oldest commissioned warship afloat earned her nickname \"Old Ironsides\" during the War of 1812 when she fought the British frigate HMS Guerriere."